using System.Reflection;

namespace Sentinel.Services;

/// <summary>
/// The single runtime source for Sentinel product, build, and commit metadata.
/// Values are derived from the assembly attributes generated by the project file.
/// </summary>
public interface IApplicationVersionProvider
{
    string ProductName { get; }
    string Version { get; }
    string DisplayVersion { get; }
    string FullVersion { get; }
    string InformationalVersion { get; }
    string? CommitHash { get; }
}

public sealed class ApplicationVersionProvider : IApplicationVersionProvider
{
    private const string FallbackProductName = "Sentinel";
    private readonly bool _isDemoMode;

    public ApplicationVersionProvider(IConfiguration configuration)
    {
        var assembly = typeof(ApplicationVersionProvider).Assembly;
        _isDemoMode = configuration.GetValue<bool>("Demo:EnableDemoMode");

        ProductName = assembly.GetCustomAttribute<AssemblyProductAttribute>()?.Product
            ?? FallbackProductName;

        InformationalVersion = assembly
            .GetCustomAttribute<AssemblyInformationalVersionAttribute>()
            ?.InformationalVersion
            ?? assembly.GetName().Version?.ToString()
            ?? "unknown";

        var separatorIndex = InformationalVersion.IndexOf('+');
        Version = separatorIndex >= 0 ? InformationalVersion[..separatorIndex] : InformationalVersion;
        CommitHash = Environment.GetEnvironmentVariable("SENTINEL_COMMIT_HASH")
            ?? (separatorIndex >= 0 ? InformationalVersion[(separatorIndex + 1)..] : null);
    }

    public string ProductName { get; }
    public string Version { get; }
    public string DisplayVersion => _isDemoMode ? $"{Version} (Demo)" : Version;
    public string FullVersion => $"v{DisplayVersion}";
    public string InformationalVersion { get; }
    public string? CommitHash { get; }
}
