using Sentinel.Models;
using System.Text;

namespace Sentinel.Services
{
    /// <summary>
    /// Validates collection mapping configurations and provides helpful warnings
    /// </summary>
    public class CollectionMappingValidationService
    {
        private readonly ILogger<CollectionMappingValidationService> _logger;

        public CollectionMappingValidationService(ILogger<CollectionMappingValidationService> logger)
        {
            _logger = logger;
        }

        /// <summary>
        /// Validates a collection mapping config and returns warnings/errors
        /// </summary>
        public ValidationResult ValidateConfig(CollectionMappingConfig config)
        {
            var result = new ValidationResult { IsValid = true };

            if (config == null)
            {
                result.IsValid = false;
                result.Errors.Add("Configuration is null");
                return result;
            }

            // Validate primary entity
            ValidatePrimaryEntity(config, result);

            // Validate related entities
            if (config.RelatedEntities != null)
            {
                foreach (var relatedEntity in config.RelatedEntities)
                {
                    ValidateRelatedEntity(relatedEntity, config.TargetEntityType, result);
                }
            }

            // Validate duplicate detection
            if (config.MatchingConfig != null)
            {
                ValidateDuplicateDetection(config.MatchingConfig, result);
            }

            return result;
        }

        private void ValidatePrimaryEntity(CollectionMappingConfig config, ValidationResult result)
        {
            if (string.IsNullOrEmpty(config.TargetEntityType))
            {
                result.Errors.Add("Primary entity type is required");
                result.IsValid = false;
                return;
            }

            if (config.RowMappings == null || !config.RowMappings.Any())
            {
                result.Warnings.Add($"No field mappings defined for primary entity '{config.TargetEntityType}'");
            }

            // Check for common required fields
            if (config.TargetEntityType == "Patient")
            {
                var hasGivenName = config.RowMappings?.Any(m => m.TargetFieldPath == "Patient.GivenName") ?? false;
                var hasFamilyName = config.RowMappings?.Any(m => m.TargetFieldPath == "Patient.FamilyName") ?? false;

                if (!hasGivenName)
                    result.Warnings.Add("Patient.GivenName is not mapped (recommended for Patient entities)");
                if (!hasFamilyName)
                    result.Warnings.Add("Patient.FamilyName is not mapped (recommended for Patient entities)");
            }
        }

        private void ValidateRelatedEntity(RelatedEntityConfig entityConfig, string primaryEntityType, ValidationResult result)
        {
            if (string.IsNullOrEmpty(entityConfig.EntityType))
            {
                result.Errors.Add("Related entity type is required");
                result.IsValid = false;
                return;
            }

            var entityType = entityConfig.EntityType;
            var mappings = entityConfig.Mappings ?? new List<RelatedEntityMapping>();

            // ? CRITICAL: Check for invalid "Id" mappings (primary key)
            foreach (var mapping in mappings)
            {
                var normalizedFieldPath = mapping.TargetFieldPath;
                if (normalizedFieldPath.Contains('.'))
                {
                    normalizedFieldPath = normalizedFieldPath.Split('.').Last();
                }

                if (normalizedFieldPath.Equals("Id", StringComparison.OrdinalIgnoreCase))
                {
                    result.Errors.Add(
                        $"? INVALID MAPPING: Cannot map to '{mapping.TargetFieldPath}'. " +
                        $"Primary keys (Id) are auto-generated by the database and cannot be manually set. " +
                        $"For ExposureEvent, use 'SourceCaseId' or 'ExposedCaseId' instead."
                    );
                    result.IsValid = false;
                }
            }

            // Check for required FK fields based on entity type
            switch (entityType)
            {
                case "Case":
                    ValidateCaseEntity(mappings, primaryEntityType, result);
                    break;

                case "ExposureEvent":
                    ValidateExposureEventEntity(mappings, result);
                    break;

                case "Contact":
                    ValidateContactEntity(mappings, result);
                    break;

                case "LabTest":
                    ValidateLabTestEntity(mappings, result);
                    break;
            }
        }

        private void ValidateCaseEntity(List<RelatedEntityMapping> mappings, string primaryEntityType, ValidationResult result)
        {
            var hasPatientId = mappings.Any(m => m.TargetFieldPath == "Case.PatientId");
            var hasDiseaseId = mappings.Any(m => m.TargetFieldPath == "Case.DiseaseId");
            var hasCaseType = mappings.Any(m => m.TargetFieldPath == "Case.Type");

            if (!hasPatientId)
            {
                result.Errors.Add("? CRITICAL: Case.PatientId is not mapped");
                result.IsValid = false;
                
                if (primaryEntityType == "Patient")
                {
                    result.Suggestions.Add("?? Add mapping: SourceType='Primary', Source='{Primary.Id}', Target='Case.PatientId'");
                }
            }

            if (!hasDiseaseId)
            {
                result.Errors.Add("? CRITICAL: Case.DiseaseId is not mapped");
                result.IsValid = false;
                result.Suggestions.Add("?? Add mapping: SourceType='Context', Source='{{Context.DiseaseId}}', Target='Case.DiseaseId'");
            }

            if (!hasCaseType)
            {
                result.Warnings.Add("?? Case.Type is not mapped (recommended for Contact/Outbreak cases)");
                result.Suggestions.Add("?? Add mapping: SourceType='Constant', Source='Contact', Target='Case.Type'");
            }
        }

        private void ValidateExposureEventEntity(List<RelatedEntityMapping> mappings, ValidationResult result)
        {
            var hasSourceCaseId = mappings.Any(m => m.TargetFieldPath == "ExposureEvent.SourceCaseId");
            var hasExposedCaseId = mappings.Any(m => m.TargetFieldPath == "ExposureEvent.ExposedCaseId");
            var hasExposureType = mappings.Any(m => m.TargetFieldPath == "ExposureEvent.ExposureType");

            if (!hasSourceCaseId)
            {
                result.Errors.Add("? CRITICAL: ExposureEvent.SourceCaseId is not mapped (source/transmitter case)");
                result.IsValid = false;
                result.Suggestions.Add("?? Add mapping: SourceType='Context', Source='{{Context.CaseId}}', Target='ExposureEvent.SourceCaseId'");
            }

            if (!hasExposedCaseId)
            {
                result.Errors.Add("? CRITICAL: ExposureEvent.ExposedCaseId is not mapped (exposed/recipient case)");
                result.IsValid = false;
                result.Suggestions.Add("?? Add mapping: SourceType='RelatedEntity', Source='{RelatedEntity.Case.Id}', Target='ExposureEvent.ExposedCaseId'");
            }

            if (!hasExposureType)
            {
                result.Warnings.Add("?? ExposureEvent.ExposureType is not mapped");
                result.Suggestions.Add("?? Add mapping: SourceType='Constant', Source='Contact' (or 3), Target='ExposureEvent.ExposureType'");
                result.Suggestions.Add("   Available options: Event (1), Location (2), Contact (3), Travel (4), Locally Acquired (5)");
            }
        }

        private void ValidateContactEntity(List<RelatedEntityMapping> mappings, ValidationResult result)
        {
            var hasPatientId = mappings.Any(m => m.TargetFieldPath == "Contact.PatientId");
            var hasCaseId = mappings.Any(m => m.TargetFieldPath == "Contact.CaseId");

            if (!hasPatientId && !hasCaseId)
            {
                result.Warnings.Add("?? Contact entity has no PatientId or CaseId mapping");
            }
        }

        private void ValidateLabTestEntity(List<RelatedEntityMapping> mappings, ValidationResult result)
        {
            var hasCaseId = mappings.Any(m => m.TargetFieldPath == "LabTest.CaseId");

            if (!hasCaseId)
            {
                result.Errors.Add("? CRITICAL: LabTest.CaseId is not mapped");
                result.IsValid = false;
                result.Suggestions.Add("?? Add mapping: SourceType='Context', Source='{{Context.CaseId}}', Target='LabTest.CaseId'");
            }
        }

        private void ValidateDuplicateDetection(MatchingConfig matchingConfig, ValidationResult result)
        {
            if (matchingConfig.MatchOnFields == null || !matchingConfig.MatchOnFields.Any())
            {
                result.Warnings.Add("?? Duplicate detection is enabled but no match fields are configured");
            }

            if (matchingConfig.ConfidenceThreshold < 0 || matchingConfig.ConfidenceThreshold > 1)
            {
                result.Errors.Add("? Confidence threshold must be between 0 and 1");
                result.IsValid = false;
            }
        }

        /// <summary>
        /// Analyzes an FK violation error and provides helpful suggestions
        /// </summary>
        public string GetHelpfulErrorMessage(Exception ex)
        {
            var message = ex.Message;
            var sb = new StringBuilder();

            // Detect FK_Cases_Patients_PatientId
            if (message.Contains("FK_Cases_Patients_PatientId"))
            {
                sb.AppendLine("? Foreign Key Violation: Case.PatientId");
                sb.AppendLine();
                sb.AppendLine("**What went wrong:**");
                sb.AppendLine("The Case (Contact) entity is trying to reference a Patient that doesn't exist.");
                sb.AppendLine();
                sb.AppendLine("**How to fix:**");
                sb.AppendLine("1. Add this mapping to your Case entity:");
                sb.AppendLine("   - SourceType: 'Primary'");
                sb.AppendLine("   - Source: '{Primary.Id}'");
                sb.AppendLine("   - Target: 'Case.PatientId'");
                sb.AppendLine("   - Required: ?");
                sb.AppendLine();
                sb.AppendLine("**SQL Fix (if you have the mapping ID):**");
                sb.AppendLine("```sql");
                sb.AppendLine("-- See fix_household_contacts_mapping.sql");
                sb.AppendLine("```");
            }
            // Detect FK_ExposureEvents_Cases_RelatedCaseId
            else if (message.Contains("FK_ExposureEvents_Cases_RelatedCaseId"))
            {
                sb.AppendLine("? Foreign Key Violation: ExposureEvent.RelatedCaseId");
                sb.AppendLine();
                sb.AppendLine("**What went wrong:**");
                sb.AppendLine("The Exposure entity is trying to reference a Case (Contact) that doesn't exist.");
                sb.AppendLine();
                sb.AppendLine("**How to fix:**");
                sb.AppendLine("1. Add this mapping to your ExposureEvent entity:");
                sb.AppendLine("   - SourceType: 'RelatedEntity'");
                sb.AppendLine("   - Source: '{RelatedEntity.Case.Id}'");
                sb.AppendLine("   - Target: 'ExposureEvent.RelatedCaseId'");
                sb.AppendLine("   - Required: ?");
            }
            // Detect FK_Cases_Diseases_DiseaseId
            else if (message.Contains("FK_Cases_Diseases_DiseaseId"))
            {
                sb.AppendLine("? Foreign Key Violation: Case.DiseaseId");
                sb.AppendLine();
                sb.AppendLine("**What went wrong:**");
                sb.AppendLine("The Case entity is missing a DiseaseId.");
                sb.AppendLine();
                sb.AppendLine("**How to fix:**");
                sb.AppendLine("1. Add this mapping to your Case entity:");
                sb.AppendLine("   - SourceType: 'Context'");
                sb.AppendLine("   - Source: '{{Context.DiseaseId}}'");
                sb.AppendLine("   - Target: 'Case.DiseaseId'");
                sb.AppendLine("   - Required: ?");
            }
            else
            {
                // Generic FK error
                sb.AppendLine("? Foreign Key Violation");
                sb.AppendLine();
                sb.AppendLine("**Error Details:**");
                sb.AppendLine(message);
                sb.AppendLine();
                sb.AppendLine("**Common Causes:**");
                sb.AppendLine("1. Missing required FK field mappings (PatientId, CaseId, DiseaseId)");
                sb.AppendLine("2. Incorrect SourceType (should be 'Primary' for PatientId, 'Context' for CaseId)");
                sb.AppendLine("3. Wrong field path (e.g., 'Case.Disease.Code' instead of 'Case.DiseaseId')");
            }

            return sb.ToString();
        }
    }

    public class ValidationResult
    {
        public bool IsValid { get; set; }
        public List<string> Errors { get; set; } = new();
        public List<string> Warnings { get; set; } = new();
        public List<string> Suggestions { get; set; } = new();

        public string GetSummary()
        {
            var sb = new StringBuilder();

            if (Errors.Any())
            {
                sb.AppendLine("## ? Errors (Must Fix)");
                foreach (var error in Errors)
                    sb.AppendLine($"- {error}");
                sb.AppendLine();
            }

            if (Warnings.Any())
            {
                sb.AppendLine("## ?? Warnings (Recommended)");
                foreach (var warning in Warnings)
                    sb.AppendLine($"- {warning}");
                sb.AppendLine();
            }

            if (Suggestions.Any())
            {
                sb.AppendLine("## ?? Suggestions");
                foreach (var suggestion in Suggestions)
                    sb.AppendLine($"- {suggestion}");
            }

            return sb.ToString();
        }

        public bool HasIssues => Errors.Any() || Warnings.Any();
    }
}
