-- Run this to see data types of all columns
SELECT 
    COLUMN_NAME, 
    DATA_TYPE,
    IS_NULLABLE,
    CHARACTER_MAXIMUM_LENGTH
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'vw_CaseContactTasksFlattened'
ORDER BY ORDINAL_POSITION;
