using System.ComponentModel.DataAnnotations;

namespace Sentinel.Models;

/// <summary>
/// History of generated test HL7 messages for tracking and replay
/// </summary>
public class HL7TestMessageHistory
{
    public Guid Id { get; set; }

    [Display(Name = "Template")]
    public Guid? TemplateId { get; set; }
    public HL7TestMessageTemplate? Template { get; set; }

    [Required]
    [Display(Name = "Raw HL7 Message")]
    public string RawHL7Message { get; set; } = string.Empty;

    [Display(Name = "File Path")]
    [StringLength(1000)]
    public string? FilePath { get; set; }

    [Display(Name = "Test Comment")]
    [StringLength(2000)]
    public string? TestComment { get; set; }

    [Display(Name = "Accession Number")]
    [StringLength(100)]
    public string? AccessionNumber { get; set; }

    [Display(Name = "Patient MRN")]
    [StringLength(100)]
    public string? PatientMRN { get; set; }

    [Display(Name = "Configuration Snapshot")]
    public string? ConfigurationSnapshot { get; set; } // JSON of the request used

    [Display(Name = "Generated HL7 Message")]
    public Guid? HL7MessageId { get; set; }
    public HL7Message? HL7Message { get; set; }

    [Display(Name = "Processing Result")]
    public string? ProcessingResultJson { get; set; } // JSON of parsed results

    [Display(Name = "Processing Status")]
    public HL7ProcessingStatus? ProcessingStatus { get; set; }

    [Display(Name = "Generated At")]
    public DateTime GeneratedAt { get; set; } = DateTime.UtcNow;

    [Display(Name = "Generated By")]
    [StringLength(450)]
    public string? GeneratedBy { get; set; }
    public ApplicationUser? GeneratedByUser { get; set; }

    [Display(Name = "Was Auto-Processed")]
    public bool WasAutoProcessed { get; set; }
}
