-- Get actual column names for view creation
-- Run this to see what columns exist in your tables

PRINT 'CaseTasks Table Columns:';
SELECT COLUMN_NAME, DATA_TYPE FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'CaseTasks' 
ORDER BY ORDINAL_POSITION;

PRINT '';
PRINT 'Cases Table Columns:';
SELECT COLUMN_NAME, DATA_TYPE FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'Cases' 
ORDER BY ORDINAL_POSITION;

PRINT '';
PRINT 'ExposureEvents Table Columns:';
SELECT COLUMN_NAME, DATA_TYPE FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'ExposureEvents' 
ORDER BY ORDINAL_POSITION;

PRINT '';
PRINT 'Outbreaks Table Columns:';
SELECT COLUMN_NAME, DATA_TYPE FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'Outbreaks' 
ORDER BY ORDINAL_POSITION;

PRINT '';
PRINT 'Patients Table Columns:';
SELECT COLUMN_NAME, DATA_TYPE FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'Patients' 
ORDER BY ORDINAL_POSITION;

PRINT '';
PRINT 'Notes Table Columns:';
SELECT COLUMN_NAME, DATA_TYPE FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'Notes' 
ORDER BY ORDINAL_POSITION;

PRINT '';
PRINT 'LabResults Table Columns:';
SELECT COLUMN_NAME, DATA_TYPE FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'LabResults' 
ORDER BY ORDINAL_POSITION;
